spring:
  application:
    name: gateway
  profiles:
    active: test
  cloud:
      gateway:
        discovery:
          locator:
            #urlExpression: "'lb://'+serviceId+'/api/'"
            enabled: true
            lower-case-service-id: true
        routes:
        - id: goods
          uri: lb://goods
          #order: 8381
          predicates:
          - Path=/goods/**
          filters:
          - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: debug
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#开启熔断配置
feign:
  hystrix.enabled: true
  httpclient.enabled: false
  okhttp.enabled: true
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 3000
      circuitBreaker.sleepWindowInMilliseconds: 3000
      circuitBreaker.forceClosed: true
      #execution.timeout.enabled: false
ribbon:
  ReadTimeout: 3000
  SocketTimeout: 3000
  #请求连接的超时时间
  ConnectTimeout: 3000
  maxAutoRetries: 0

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000
#    "GoodsService#testTimeOut()":
#          execution:
#            isolation:
#              thread:
#                timeoutInMilliseconds: 1000
#
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000
#
#  #开启gzip压缩
#  compression:
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true
