spring:
  application:
    name: gateway
  profiles:
    active: test
  cloud:
      gateway:
        discovery:
                locator:
                  #urlExpression: "'lb://'+serviceId+'/api/'"
                  enabled: true
                  lower-case-service-id: true
                  # 网关接口网址 http://gateway/api/{module}/test 转换成 http://{module}/test
                  predicates:
                  - name: Path
                    args:
                      pattern: "'/api/'+serviceId+'/**'"
                  filters:
                  - name: RewritePath
                    args:
                      regexp: "'/api/' + serviceId + '/(?<remaining>.*)'"
                      replacement: "'/$\\{remaining}'"
        routes:
        - id: goods
          uri: lb://goods
          #order: 8381
          predicates:
          - Path=/goods/**
          filters:
          - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: debug
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # Eureka服务注册中心会将自己作为客户端来尝试注册它自己，必須禁止
#    register-with-eureka: false
#    fetch-registry: false

#开启熔断配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
  hystrix:
    enabled: true
  httpclient.enabled: false
  okhttp:
    enabled: true



#hystrix:
#  command:
#    default:
#      execution.isolation.thread.timeoutInMilliseconds: 300000
#      circuitBreaker.sleepWindowInMilliseconds: 300000
#      circuitBreaker.forceClosed: true
#      #execution.timeout.enabled: false
#  #请求处理的超时时间
#ribbon:
#  ReadTimeout: 300000
#  SocketTimeout: 300000
#  #请求连接的超时时间
#  ConnectTimeout: 30000
#  maxAutoRetries: 0