spring:
  profiles:
    active: dev
  application:
    name: eureka
server:
  port: 8761
eureka:
  client:
    #false:不作为一个客户端注册到注册中心
    register-with-eureka: false
    #为true时，可以启动，但报异常：Cannot execute request on any known server
    fetch-registry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  instance:
#    hostname: localhost


