spring:
  profiles:
    active: dev
  application:
    name: goods
server:
  port: ${server.port}
# 配置Eureka Server 信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # 自定义实例编号
  instance:
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true


