spring:
  profiles:
    active: @env@
  application:
    name: goods
server:
  port: ${server.port}
# 配置Eureka Server 信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # 自定义实例编号
  instance:
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
system:
  config:
    value: 1222

#开启熔断配置
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: basic
  hystrix.enabled: true
  httpclient.enabled: true
  okhttp.enabled: true

#ribbon:
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true
#  ReadTimeout: 600
#  SocketTimeout: 600
#  #请求连接的超时时间
#  ConnectTimeout: 600
#  maxAutoRetries: 0
#
#hystrix:
#  command:
#    default:
#      execution.isolation.thread.timeoutInMilliseconds: 600
#      circuitBreaker.sleepWindowInMilliseconds: 600
#      circuitBreaker.forceClosed: true



